#LarbyDB config
# If set to true, will ask the user to input parameters on launch:
manual-config false

# sets the port:
port 8080

# sets the web interface port
web-interface-port 8081

# How many hashtables the db has (minimum 2):
num-tables 2

# Should the db perform automatic backups:
# true | false
allow-backup true

# Sets the time interval between performing backups:
# h - hours
# m - minutes
# anything else counts as seconds.
# Only positive integer values are allowed.
backup-interval 30m

# Generate the authentication key:
generate-key true

# Enable Hypertext Transfer Protocol:
enable-http false

# Should the db load from a backup file:
# true  - load from backups
# false - do not load from backups
# ask   - ask the user whether to load from the backup file
load-backup ask